Masaüstü/Blood-Donation/RubymineProjects/config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'facebookusers#create', via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'facebookusers#destroy', as: 'signout',via: :get
  root 'users#index'
  
  get 'users/homepage'
  get '/users/emergency'
  get '/users/blood_donors'
  get '/users/blood_donors_unregister'
  get 'users/change_status'
  get 'users/notifications'
  get 'users/facebook_share'
  get 'users/donation_centers'
  get 'users/donor_hospitals'
  get 'users/blood_friends'
  get 'users/blood_friends'
  post "change_status" => "users#status_change"

  
  post '/session/index' => "sessions#login"
  resources :sessions
  resources :users

end

Masaüstü/Blood-Donation/RubymineProjects/app/models/facebook_user.rb
class FacebookUser < ActiveRecord::Base

	#attr_accessor :provider, :fbkuser_id, :name, :oauth_token, :oauth_expires_at, :email
	def self.from_omniauth(auth)

			user=FacebookUser.find_by_fbkuser_id(auth.uid)
			if user.present?
				#return user if alreay registered 
				user
			else
				#register the user
				user=FacebookUser.new
				user.provider=auth.provider
				user.email=auth.info.email
				user.fbkuser_id=auth.uid
			    user.fbkuser_name=auth.info.name
			    user.oauth_token=auth.credentials.token
			    user.oauth_expires_at=Time.at(auth.credentials.expires_at)
			    if user.save
			    	user
			    else
			    	false
			    end

			end

	end
end

Masaüstü/Blood-Donation/RubymineProjects/app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password_confirmation

	validates :username, presence: true
	validates :password, presence: true
	validates :name, presence: true
	validates :phone_no, presence: true
	validates :email, presence: true
	validates :address, presence: true
	validates :id_no, presence: true
	validates_uniqueness_of :username
	validates_uniqueness_of :id_no
	validates_uniqueness_of :phone_no
	validates_confirmation_of :password, presence: true

	before_save :encrypt_password

	def self.authenticate(username,password)
		user=User.find_by_username(username)

	end


	def encrypt_password
		if password.present?

		end
	end
end

Masaüstü/Blood-Donation/RubymineProjects/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  			@current_user ||= User.find(session[:user_id]) if session[:user_id]
  			@current_user ||= FacebookUser.find(session[:fbkuser_id]) if session[:fbkuser_id]
  end
  
end

Masaüstü/Blood-Donation/RubymineProjects/app/controllers/facebookusers_controller.rb
class FacebookusersController < ApplicationController

	def create
		fbkuser=FacebookUser.from_omniauth(request.env["omniauth.auth"])
		if fbkuser.present?
			session[:fbkuser_id]=fbkuser.id
			redirect_to users_homepage_path
		else
			redirect_to root_path, :notice=>"Could not Log In"
		end
		
	end

	def destroy
		session[:fbkuser_id]=nil
		redirect_to root_url, :notice=>"Logged Out"
	end

end

Masaüstü/Blood-Donation/RubymineProjects/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	  
    def new
  		@user=User.new
  	end

    def index
      render :layout => 'index-layout'
    end

  	def login 
  	
  		user=User.authenticate(params[:User][:username],params[:User][:password])

  		if user
  			session[:user_id]=user.id
  			redirect_to users_homepage_path  ,:notice => "Logged in successfully"
  		else
  			redirect_to root_path, :notice => "Unable to Login"
  		end
  	end
  
  	def destroy
      	session[:user_id]=nil
      	redirect_to root_path, :notice=>"Logged Out successfully"
  	end
end

Masaüstü/Blood-Donation/RubymineProjects/app/controllers/users_controller.rb
class UsersController < ApplicationController

    layout "userhome_layout"

  	def new
  		@user=User.new
      render :layout => 'index-layout'
  	end

  	def index 
      render :layout => 'index-layout'
  	end

  	def create
  		@user=User.new(user_params)
  		if @user.save
    			redirect_to root_path, :notice => "Registered Successfully" 
  		else
  	  		render 'new'
  		end
   	end

    def edit
      if session[:user_id].present?
        @user=User.find(session[:user_id])
        render 'edit'
      else
        render 'homepage', :notice=>"Login to Edit"
      end
    end

    def update
      @user = User.find(session[:user_id])

 
      if @user.update(user_params)
        redirect_to users_homepage_path, :notice => "Successfully Updated !!"
      else
        render 'edit'
      end
    end

    def user_params
      params.require(:user).permit(:username, :password, :name, :blood_group, :phone_no, :email, :address, :id_no)
    end


    def change_status
      @user = User.find(session[:user_id]) if session[:user_id]
      @user = FacebookUser.find(session[:fbkuser_id]) if session[:fbkuser_id]
    end

    def status_change
      @user = User.find(session[:user_id]) if session[:user_id]
     # @user = FacebookUser.find(session[:fbkuser_id]) if session[:fbkuser_id]
      if session[:user_id]
        @arg=params.require(:user).permit(:status)
     # else
      #  @arg=params.require(:facebook_user).permit(:status)
      end 

      if @user.update(@arg)
        redirect_to users_homepage_path, :notice => "Status Successfully Updated"
      else
        render 'change_status', :notice => "Could Not Update"
      end
    end

    def homepage
      @user=User.find(session[:user_id]) if session[:user_id]
      #@user=FacebookUser.find(session[:fbkuser_id]) if session[:fbkuser_id]
      render :layout => 'userhome_layout'
    end

    def blood_donors
      render :layout => 'userhome_layout'
    end

    def blood_donors_unregister
      render :layout => 'index-layout'
    end

    def emergency
      render :layout => 'index-layout'
    end



 	#private
  	

end

Masaüstü/Blood-Donation/RubymineProjects/app/helpers/application_helper.rb
module ApplicationHelper
end

Masaüstü/Blood-Donation/RubymineProjects/app/helpers/sessions_helper.rb
module SessionsHelper
end

Masaüstü/Blood-Donation/RubymineProjects/app/helpers/users_helper.rb
module UsersHelper
end

Masaüstü/Blood-Donation/RubymineProjects/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloodDonationApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
	Hi <%= current_user.name %>
	<%= @path=sessions_destroy_path if session[:user_id] %>
	<%= @path=signout_path if session[:fbkuser_id] %>
	<%= link_to "Log out",  @path %>
<% end %>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<%= yield %>

</body>
</html>

Masaüstü/Blood-Donation/RubymineProjects/app/views/layouts/index-layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloodDonationApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  
</head>
<body>
	<h2 class="header"><center>Blood Donation</center></h2>

	<div class="link-box">
		<center><%= link_to "Emergency", users_emergency_path %></center>
	</div>
	<br />
	<div class="link-box">
    <center><%= link_to "Log In", sessions_path %></center>
	</div>
	<br />
	<div class="link-box">
    <center><%= link_to "Register", new_user_path %></center>
	</div>
	<div class="index-body">
		 <% flash.each do |key, value| %>
  				<%= content_tag :div, value, class: "flash #{key}" %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

Masaüstü/Blood-Donation/RubymineProjects/app/views/layouts/userhome_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloodDonationApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  
</head>
<body>
	
	

	<h2 class="header"><center>Blood Donation</center></h2>

	<div id="contentWrapper">
	  	<div id="contentLeft">
		    <ul id="leftNavigation">
		    	<li><%= link_to "Home", users_homepage_path %><i class="fa leftNavIcon"></i></li>
		    	<li><%= link_to "View All Blood Donors", users_blood_donors_path %><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "View Blood Friends", users_blood_friends_path %><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "View Donor Hospitals", users_donor_hospitals_path %><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "Change Your Status", users_change_status_path %><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "Notifications", users_notifications_path %><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "Blood Donation Centers", users_donation_centers_path %><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "Update Profile", edit_user_path(session[:user_id]) if session[:user_id]%><i class="fa leftNavIcon"></i></li>
				<li><%= link_to "Invite a Friend !!", users_facebook_share_path %><i class="fa leftNavIcon"></li>
			</ul>
		</div>
		  	
		<div id="contentRight">

		    <% flash.each do |key, value| %>
  				<%= content_tag :div, value, class: "flash #{key}" %>
			<% end %>
			<% if current_user %>
				Hi <%= current_user.name if session[:user_id] 
						current_user.fbkuser_name if session[:fbkuser_id]%>
				<div>
					<% if session[:user_id] %>
							<%= link_to "Log out",  session_path(current_user.id), method: :delete %>
					<%else%>
							<%= link_to "Log out",  signout_path %>
					<% end %>
				</div>
			<% end %>
			<br /><br />
			<%= yield %>

      	</div>
	</div>
	
	

</body>
</html>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="js/object/VerticalNavigation.min.js"></script>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/_form.html.erb
<div class>
	<%= form_for @user do |f| %>
	 
	  <% if @user.errors.any? %>
	  	
	    <div id="error_explanation">
	      <h2>
	        <%= pluralize(@user.errors.count, "error") %> prohibited
	        this article from being saved:
	      </h2>
	      <ul>
	        <% @user.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>
	 
	  <p>
	    <%= f.label :Username %><br />
	    <%= f.text_field :username %>
	  </p>
	  

	  <p>
	    <%= f.label :Password %><br />
	    <%= f.password_field :password %>
	  </p>
	  

	  <p>
	    <%= f.label :Password_confirmation %><br />
	    <%= f.password_field :password_confirmation %>
	  </p>
	  

	  <p>
	    <%= f.label :Name %><br />
	    <%= f.text_field :name %>
	  </p>

	  <p>
	    <%= f.label :Blood_group %><br />
	    <%= f.text_field :blood_group %>
	  </p>
	  

	  <p>
	    <%= f.label :Phone_No %><br />
	    <%= f.text_field :phone_no %>
	  </p>
	  

	  <p>
	    <%= f.label :Email %><br />
	    <%= f.text_field :email %>
	  </p>
	  

	  <p>
	    <%= f.label :Address %><br />
	    <%= f.text_area :address %>
	  </p>

	  <p>
	    <%= f.label :Identification_Number %><br />
	    <%= f.text_field :id_no %>
	  </p>
	  
	 
	  <p>
	    <%= f.submit %>
	  </p>
	 
	<% end %>
</div>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/_userdetails.html.erb
<div>
  <table class="display-table">


    <tr><td>Email </td><td><%= @user.email if @user.email.present? %></td></tr>

    <tr><td>Status  </td><td><%= @user.status if @user.status.present? %></td></tr>
    <!--
	<tr><td>Phone No  </td><td><%#= @user.phone_no if @user.phone_no.present? %></td></tr>
	<tr><td>Username </td><td><%#= @user.username if @user.username.present? %></td></tr>
	<tr><td>Address </td><td><%#= @user.address if @user.address.present? %></td></tr>
	<tr><td>Id No </td><td><%#= @user.id_no if @user.id_no.present? %></td></tr>
	<tr><td>Blood Group </td><td><%#= @user.blood_group if @user.name.present? %></td></tr>
	<tr><td>Ranking </td><td><%#= if @user.ranking.present? 
									@user.ranking 
								else 
									0 
								end %></td></tr>
	-->
  </table>
</div>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/blood_donors.html.erb
<h3>All Blood Donors : </h3>
<%#= form_for :user do |f| %>
<table class="display-table">
	<thead>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Blood Group</th>
		<th>Identification No</th>
		<th>Status</th>
		<th>Send Friend Request</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Çağla</td>
		<td>cgla.baran@gmail.com</td>
		<td>A+</td>
		<td>625722537</td>
		<td>Available</td>
		<td><input type="button" name="add" value="Add as a friend"</input></td>
	</tr>

  <tr>
    <td>Elif</td>
    <td>eliff@gmail.com</td>
    <td>AB+</td>
    <td>15254437</td>
    <td>Available</td>
    <td><input type="button" name="add" value="Add as a friend"</input></td>
  </tr>

  <tr>
    <td>Ahmet</td>
    <td>ahmett@gmail.com</td>
    <td>B+</td>
    <td>358851537</td>
    <td>Available</td>
    <td><input type="button" name="add" value="Add as a friend"</input></td>
  </tr>

  <tr>
    <td>Nurdan</td>
    <td>nurdann@gmail.com</td>
    <td>B+</td>
    <td>254412837</td>
    <td>Busy</td>
    <td><input type="button" name="add" value="Add as a friend"</input></td>
  </tr>
	</tbody>
</table>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/blood_donors_unregister.html.erb
<h3>All Blood Donors : </h3>
<%#= form_for :user do |f| %>
<table class="display-table">
	<thead>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Blood Group</th>
		<th>Identification No</th>
		<th>Status</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Feriha</td>
		<td>feriha@gmail.com</td>
		<td>A+</td>
		<td>625722537</td>
		<td>Available</td>
	</tr>
	</tbody>
</table>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/blood_friends.html.erb
You have 0 friends till now.

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/change_status.html.erb
<h3>Change Status</h3>
<%= form_for :facebook_user, url: change_status_path do |f| %>
	<%= f.radio_button :status, "Available" %>
	<%= f.label :Status, "Available" %><br /><br />
	<%= f.radio_button :status, "Busy" %>
	<%= f.label :Status, "Busy" %>	
	<br /><br />
	<%= f.submit "Change" %>
<% end %>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/donation_centers.html.erb
<h3> List of donation centers </h3>
<%#= form_for :user do |f| %>
<table class="display-table">
	<thead>
	<tr>
		<th>Name</th>
		<th>Phone Number</th>
		<th>Address</th>
		<th>Status</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Kan Merkezi</td>
		<td>1251</td>
		<td>gebze </td>
		<td>Available</td>
	</tr>
	</tbody>
</table>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/donor_hospitals.html.erb
<h3> List of Donor Hospitals </h3>
<%#= form_for :user do |f| %>
<table class="display-table">
	<thead>
	<tr>
		<th>Name</th>
		<th>Phone Number</th>
		<th>Address</th>
		<th>Status</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Yavuz Selim Devlet Hastanesi</td>
		<td>21625152</td>
		<td>kartal bla bla</td>
		<td>Available</td>
	</tr>

  <tr>
  <td>Kızılay</td>
  <td>216777155</td>
  <td>adres .....</td>
  <td>Available</td>
  </tr>
	</tbody>
</table>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/edit.html.erb
<h3><center>Update Profile</center></h3>

<%= render 'form' %>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/emergency.html.erb
<%= link_to "Search All Donors", users_blood_donors_unregister_path  %>&nbsp&nbsp
<%= link_to "Search By Blood Group" %>&nbsp&nbsp
<%= link_to "Search Universal Donors" %>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/facebook_share.html.erb
<h3>Send an invite to a friend </h3><br /><br />
<form>
Email : <input type="text" name="email">
<input type="submit" name="submit" value="Send an invite !" >
</form>
<br />
OR <h3>Share Via Facebook</h3>

<div id=fb-root></div>
<div class="fb-share-button" data-href="http://loacalhost:3000" data-layout="button"></div>


<script type="text/javascript">
    setInterval("my_function();",1000);
    function my_function(){
      document.getElementById("location.href");
    }
</script>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/homepage.html.erb
You have <%= User.all.count-1 %> members ready to donate blood for you !!
<br /><br />
<%= render :partial => "userdetails" %>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/new.html.erb
<h3><center>Register</center></h3>

<%= render 'form' %>

Masaüstü/Blood-Donation/RubymineProjects/app/views/users/notifications.html.erb
<h3> Notifications </h3><br />
<h5>Friend Requests</h5> 
<table class="display-table">
	<thead>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Address</th>
		<th>Phone number</th>
		<th>Blood Group</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Erkan</td>
		<td>abc@xyz.com</td>
		<td>adres ....</td>
		<td>47589</td>
		<td>A+</td>
		<td><input type="button" name="add" value="Accept Request" ></td>
	</tr>
	</tbody>
</table>

<h5> Blood Requests </h5>
<table class="display-table">
	<thead>
	<tr>
		<th>Requester Name</th>
		<th>Email</th>
		<th>Address</th>
		<th>Phone number</th>
		<th>Blood group needed</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>Canan</td>
		<td>canan@gmail.com</td>
		<td>gebze teknik üniversitesi</td>
		<td>2512</td>
		<td>A+</td>
	</tr>
	</tbody>
</table>